export const ALL_SHIRT_REQUEST = 'ALL_SHIRT_REQUEST'
export const ALL_SHIRT_SUCCESS = 'ALL_SHIRT_SUCCESS'
export const ALL_SHIRT_FAIL = 'ALL_SHIRT_FAIL'


export const SHIRT_DETAILS_REQUEST = 'SHIRT_DETAILS_REQUEST'
export const SHIRT_DETAILS_SUCCESS = 'SHIRT_DETAILS_SUCCESS'
export const SHIRT_DETAILS_FAIL = 'SHIRT_DETAILS_FAIL'


export const ALL_JACKET_REQUEST = 'ALL_JACKET_REQUEST'
export const ALL_JACKET_SUCCESS = 'ALL_JACKET_SUCCESS'
export const ALL_JACKET_FAIL = 'ALL_JACKET_FAIL'


export const JACKET_DETAILS_REQUEST = 'JACKET_DETAILS_REQUEST'
export const JACKET_DETAILS_SUCCESS = 'JACKET_DETAILS_SUCCESS'
export const JACKET_DETAILS_FAIL = 'JACKET_DETAILS_FAIL'


export const ALL_JEANS_REQUEST = 'ALL_JEANS_REQUEST'
export const ALL_JEANS_SUCCESS = 'ALL_JEANS_SUCCESS'
export const ALL_JEANS_FAIL = 'ALL_JEANS_FAIL'


export const JEANS_DETAILS_REQUEST = 'JEANS_DETAILS_REQUEST'
export const JEANS_DETAILS_SUCCESS = 'JEANS_DETAILS_SUCCESS'
export const JEANS_DETAILS_FAIL = 'JEANS_DETAILS_FAIL'


export const ALL_KURTA_REQUEST = 'ALL_KURTA_REQUEST'
export const ALL_KURTA_SUCCESS = 'ALL_KURTA_SUCCESS'
export const ALL_KURTA_FAIL = 'ALL_KURTA_FAIL'


export const KURTA_DETAILS_REQUEST = 'KURTA_DETAILS_REQUEST'
export const KURTA_DETAILS_SUCCESS = 'KURTA_DETAILS_SUCCESS'
export const KURTA_DETAILS_FAIL = 'KURTA_DETAILS_FAIL'


export const ALL_SPORTS_REQUEST = 'ALL_SPORTS_REQUEST'
export const ALL_SPORTS_SUCCESS = 'ALL_SPORTS_SUCCESS'
export const ALL_SPORTS_FAIL = 'ALL_SPORTS_FAIL'


export const SPORTS_DETAILS_REQUEST = 'SPORTS_DETAILS_REQUEST'
export const SPORTS_DETAILS_SUCCESS = 'SPORTS_DETAILS_SUCCESS'
export const SPORTS_DETAILS_FAIL = 'SPORTS_DETAILS_FAIL'


export const ALL_TSHIRT_REQUEST = 'ALL_TSHIRT_REQUEST'
export const ALL_TSHIRT_SUCCESS = 'ALL_TSHIRT_SUCCESS'
export const ALL_TSHIRT_FAIL = 'ALL_TSHIRT_FAIL'


export const TSHIRT_DETAILS_REQUEST = 'TSHIRT_DETAILS_REQUEST'
export const TSHIRT_DETAILS_SUCCESS = 'TSHIRT_DETAILS_SUCCESS'
export const TSHIRT_DETAILS_FAIL = 'TSHIRT_DETAILS_FAIL'
